feat: add WooBuyBackSwap
woonetwork/WooStakingV2 pull request #47
Opened 2024-03-30 12:59 UTC by toprince

2024-03-30 16:50 UTC, fb-alexcq commented on contracts/WooBuybackSwap.sol
> +        ILBRouter.Path memory usdcPath;
Better to make this init logic into a private method.

2024-03-30 16:50 UTC, fb-alexcq commented on contracts/WooBuybackSwap.sol
> +    address public unirouter;
uniRouter -> lbRouter ; same for event name.

2024-03-30 16:51 UTC, fb-alexcq commented on contracts/WooBuybackSwap.sol
> +import {EnumerableSet} from "@openzeppelin/contracts/utils/structs/EnumerableSet.sol";
not needed.

2024-03-30 16:51 UTC, fb-alexcq commented on contracts/WooBuybackSwap.sol
> +import {IERC20, SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
SafeERC20 not needed.

2024-03-30 16:52 UTC, fb-alexcq requested changes
Per inline comments.

2024-04-02 08:50 UTC, 0xmer1in approved these changes

2024-04-02 08:52 UTC, fb-alexcq approved these changes

2024-04-02 08:52 UTC, fb-alexcq commented on contracts/WooBuybackSwap.sol
> +        slippage = 50;
50 --> 300 ?

2024-04-02 09:53 UTC, merged